# Generated by Django 5.2.5 on 2025-09-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add books'), ('can_change_book', 'Can change books'), ('can_delete_book', 'Can delete books'), ('can_view', 'Can view books')]},
        ),
    ]
